module Proto.Triples exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/triples.proto

import Json.Decode as JD
import Json.Encode as JE
import Protobuf exposing (..)


type ClaimType
    = ClaimMatch -- 0
    | ClaimNomatch -- 1


claimTypeDecoder : JD.Decoder ClaimType
claimTypeDecoder =
    let
        lookup s =
            case s of
                "CLAIM_MATCH" ->
                    ClaimMatch

                "CLAIM_NOMATCH" ->
                    ClaimNomatch

                _ ->
                    ClaimMatch
    in
    JD.map lookup JD.string


claimTypeDefault : ClaimType
claimTypeDefault =
    ClaimMatch


claimTypeEncoder : ClaimType -> JE.Value
claimTypeEncoder v =
    let
        lookup s =
            case s of
                ClaimMatch ->
                    "CLAIM_MATCH"

                ClaimNomatch ->
                    "CLAIM_NOMATCH"
    in
    JE.string <| lookup v


type alias Claim =
    { type_ : ClaimType -- 1
    , cards : List Int -- 2
    }


claimDecoder : JD.Decoder Claim
claimDecoder =
    JD.lazy <|
        \_ ->
            decode Claim
                |> required "type" claimTypeDecoder claimTypeDefault
                |> repeated "cards" JD.int


claimEncoder : Claim -> JE.Value
claimEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ requiredFieldEncoder "type" claimTypeEncoder claimTypeDefault v.type_
            , repeatedFieldEncoder "cards" JE.int v.cards
            ]


type alias UpdateEvent =
    { eventOneof : EventOneof
    }


type EventOneof
    = EventOneofUnspecified
    | Join UpdateEvent_EventJoin
    | Claimed UpdateEvent_EventClaimed


eventOneofDecoder : JD.Decoder EventOneof
eventOneofDecoder =
    JD.lazy <|
        \_ ->
            JD.oneOf
                [ JD.map Join (JD.field "join" updateEvent_EventJoinDecoder)
                , JD.map Claimed (JD.field "claimed" updateEvent_EventClaimedDecoder)
                , JD.succeed EventOneofUnspecified
                ]


eventOneofEncoder : EventOneof -> Maybe ( String, JE.Value )
eventOneofEncoder v =
    case v of
        EventOneofUnspecified ->
            Nothing

        Join x ->
            Just ( "join", updateEvent_EventJoinEncoder x )

        Claimed x ->
            Just ( "claimed", updateEvent_EventClaimedEncoder x )


updateEventDecoder : JD.Decoder UpdateEvent
updateEventDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateEvent
                |> field eventOneofDecoder


updateEventEncoder : UpdateEvent -> JE.Value
updateEventEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ eventOneofEncoder v.eventOneof
            ]


type alias UpdateEvent_EventJoin =
    { name : String -- 1
    }


updateEvent_EventJoinDecoder : JD.Decoder UpdateEvent_EventJoin
updateEvent_EventJoinDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateEvent_EventJoin
                |> required "name" JD.string ""


updateEvent_EventJoinEncoder : UpdateEvent_EventJoin -> JE.Value
updateEvent_EventJoinEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ requiredFieldEncoder "name" JE.string "" v.name
            ]


type alias UpdateEvent_EventClaimed =
    { name : String -- 1
    , type_ : ClaimType -- 2
    , result : UpdateEvent_EventClaimed_Result -- 3
    }


type UpdateEvent_EventClaimed_Result
    = UpdateEvent_EventClaimed_Correct -- 0
    | UpdateEvent_EventClaimed_Wrong -- 1
    | UpdateEvent_EventClaimed_Late -- 2


updateEvent_EventClaimedDecoder : JD.Decoder UpdateEvent_EventClaimed
updateEvent_EventClaimedDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateEvent_EventClaimed
                |> required "name" JD.string ""
                |> required "type" claimTypeDecoder claimTypeDefault
                |> required "result" updateEvent_EventClaimed_ResultDecoder updateEvent_EventClaimed_ResultDefault


updateEvent_EventClaimed_ResultDecoder : JD.Decoder UpdateEvent_EventClaimed_Result
updateEvent_EventClaimed_ResultDecoder =
    let
        lookup s =
            case s of
                "CORRECT" ->
                    UpdateEvent_EventClaimed_Correct

                "WRONG" ->
                    UpdateEvent_EventClaimed_Wrong

                "LATE" ->
                    UpdateEvent_EventClaimed_Late

                _ ->
                    UpdateEvent_EventClaimed_Correct
    in
    JD.map lookup JD.string


updateEvent_EventClaimed_ResultDefault : UpdateEvent_EventClaimed_Result
updateEvent_EventClaimed_ResultDefault =
    UpdateEvent_EventClaimed_Correct


updateEvent_EventClaimedEncoder : UpdateEvent_EventClaimed -> JE.Value
updateEvent_EventClaimedEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ requiredFieldEncoder "name" JE.string "" v.name
            , requiredFieldEncoder "type" claimTypeEncoder claimTypeDefault v.type_
            , requiredFieldEncoder "result" updateEvent_EventClaimed_ResultEncoder updateEvent_EventClaimed_ResultDefault v.result
            ]


updateEvent_EventClaimed_ResultEncoder : UpdateEvent_EventClaimed_Result -> JE.Value
updateEvent_EventClaimed_ResultEncoder v =
    let
        lookup s =
            case s of
                UpdateEvent_EventClaimed_Correct ->
                    "CORRECT"

                UpdateEvent_EventClaimed_Wrong ->
                    "WRONG"

                UpdateEvent_EventClaimed_Late ->
                    "LATE"
    in
    JE.string <| lookup v


type alias UpdateChange =
    { changeOneof : ChangeOneof
    }


type ChangeOneof
    = ChangeOneofUnspecified
    | Deal UpdateChange_ChangeDeal
    | Match UpdateChange_ChangeMatch
    | Move UpdateChange_ChangeMove


changeOneofDecoder : JD.Decoder ChangeOneof
changeOneofDecoder =
    JD.lazy <|
        \_ ->
            JD.oneOf
                [ JD.map Deal (JD.field "deal" updateChange_ChangeDealDecoder)
                , JD.map Match (JD.field "match" updateChange_ChangeMatchDecoder)
                , JD.map Move (JD.field "move" updateChange_ChangeMoveDecoder)
                , JD.succeed ChangeOneofUnspecified
                ]


changeOneofEncoder : ChangeOneof -> Maybe ( String, JE.Value )
changeOneofEncoder v =
    case v of
        ChangeOneofUnspecified ->
            Nothing

        Deal x ->
            Just ( "deal", updateChange_ChangeDealEncoder x )

        Match x ->
            Just ( "match", updateChange_ChangeMatchEncoder x )

        Move x ->
            Just ( "move", updateChange_ChangeMoveEncoder x )


updateChangeDecoder : JD.Decoder UpdateChange
updateChangeDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange
                |> field changeOneofDecoder


updateChangeEncoder : UpdateChange -> JE.Value
updateChangeEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ changeOneofEncoder v.changeOneof
            ]


type alias UpdateChange_Position =
    { x : Int -- 1
    , y : Int -- 2
    }


updateChange_PositionDecoder : JD.Decoder UpdateChange_Position
updateChange_PositionDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange_Position
                |> required "x" JD.int 0
                |> required "y" JD.int 0


updateChange_PositionEncoder : UpdateChange_Position -> JE.Value
updateChange_PositionEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ requiredFieldEncoder "x" JE.int 0 v.x
            , requiredFieldEncoder "y" JE.int 0 v.y
            ]


type alias UpdateChange_ChangeDeal =
    { places : List UpdateChange_ChangeDeal_Place -- 1
    }


updateChange_ChangeDealDecoder : JD.Decoder UpdateChange_ChangeDeal
updateChange_ChangeDealDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange_ChangeDeal
                |> repeated "places" updateChange_ChangeDeal_PlaceDecoder


updateChange_ChangeDealEncoder : UpdateChange_ChangeDeal -> JE.Value
updateChange_ChangeDealEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ repeatedFieldEncoder "places" updateChange_ChangeDeal_PlaceEncoder v.places
            ]


type alias UpdateChange_ChangeDeal_Place =
    { position : Maybe UpdateChange_Position -- 1
    , card : Int -- 2
    }


updateChange_ChangeDeal_PlaceDecoder : JD.Decoder UpdateChange_ChangeDeal_Place
updateChange_ChangeDeal_PlaceDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange_ChangeDeal_Place
                |> optional "position" updateChange_PositionDecoder
                |> required "card" JD.int 0


updateChange_ChangeDeal_PlaceEncoder : UpdateChange_ChangeDeal_Place -> JE.Value
updateChange_ChangeDeal_PlaceEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ optionalEncoder "position" updateChange_PositionEncoder v.position
            , requiredFieldEncoder "card" JE.int 0 v.card
            ]


type alias UpdateChange_ChangeMatch =
    { positions : List UpdateChange_Position -- 1
    }


updateChange_ChangeMatchDecoder : JD.Decoder UpdateChange_ChangeMatch
updateChange_ChangeMatchDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange_ChangeMatch
                |> repeated "positions" updateChange_PositionDecoder


updateChange_ChangeMatchEncoder : UpdateChange_ChangeMatch -> JE.Value
updateChange_ChangeMatchEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ repeatedFieldEncoder "positions" updateChange_PositionEncoder v.positions
            ]


type alias UpdateChange_ChangeMove =
    { moves : List UpdateChange_ChangeMove_MoveOne -- 1
    }


updateChange_ChangeMoveDecoder : JD.Decoder UpdateChange_ChangeMove
updateChange_ChangeMoveDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange_ChangeMove
                |> repeated "moves" updateChange_ChangeMove_MoveOneDecoder


updateChange_ChangeMoveEncoder : UpdateChange_ChangeMove -> JE.Value
updateChange_ChangeMoveEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ repeatedFieldEncoder "moves" updateChange_ChangeMove_MoveOneEncoder v.moves
            ]


type alias UpdateChange_ChangeMove_MoveOne =
    { from : Maybe UpdateChange_Position -- 1
    , to : Maybe UpdateChange_Position -- 2
    }


updateChange_ChangeMove_MoveOneDecoder : JD.Decoder UpdateChange_ChangeMove_MoveOne
updateChange_ChangeMove_MoveOneDecoder =
    JD.lazy <|
        \_ ->
            decode UpdateChange_ChangeMove_MoveOne
                |> optional "from" updateChange_PositionDecoder
                |> optional "to" updateChange_PositionDecoder


updateChange_ChangeMove_MoveOneEncoder : UpdateChange_ChangeMove_MoveOne -> JE.Value
updateChange_ChangeMove_MoveOneEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ optionalEncoder "from" updateChange_PositionEncoder v.from
            , optionalEncoder "to" updateChange_PositionEncoder v.to
            ]


type alias Update =
    { msgid : Int -- 1
    , updateOneof : UpdateOneof
    }


type UpdateOneof
    = UpdateOneofUnspecified
    | Change UpdateChange
    | Event UpdateEvent


updateOneofDecoder : JD.Decoder UpdateOneof
updateOneofDecoder =
    JD.lazy <|
        \_ ->
            JD.oneOf
                [ JD.map Change (JD.field "change" updateChangeDecoder)
                , JD.map Event (JD.field "event" updateEventDecoder)
                , JD.succeed UpdateOneofUnspecified
                ]


updateOneofEncoder : UpdateOneof -> Maybe ( String, JE.Value )
updateOneofEncoder v =
    case v of
        UpdateOneofUnspecified ->
            Nothing

        Change x ->
            Just ( "change", updateChangeEncoder x )

        Event x ->
            Just ( "event", updateEventEncoder x )


updateDecoder : JD.Decoder Update
updateDecoder =
    JD.lazy <|
        \_ ->
            decode Update
                |> required "msgid" JD.int 0
                |> field updateOneofDecoder


updateEncoder : Update -> JE.Value
updateEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ requiredFieldEncoder "msgid" JE.int 0 v.msgid
            , updateOneofEncoder v.updateOneof
            ]
