// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/triples.proto

/*
Package triples is a generated protocol buffer package.

It is generated from these files:
	proto/triples.proto

It has these top-level messages:
	Claim
	UpdateEvent
	UpdateChange
	Update
*/
package triples

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClaimType int32

const (
	ClaimType_CLAIM_MATCH   ClaimType = 0
	ClaimType_CLAIM_NOMATCH ClaimType = 1
)

var ClaimType_name = map[int32]string{
	0: "CLAIM_MATCH",
	1: "CLAIM_NOMATCH",
}
var ClaimType_value = map[string]int32{
	"CLAIM_MATCH":   0,
	"CLAIM_NOMATCH": 1,
}

func (x ClaimType) String() string {
	return proto.EnumName(ClaimType_name, int32(x))
}
func (ClaimType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpdateEvent_EventClaimed_Result int32

const (
	UpdateEvent_EventClaimed_CORRECT UpdateEvent_EventClaimed_Result = 0
	UpdateEvent_EventClaimed_WRONG   UpdateEvent_EventClaimed_Result = 1
	UpdateEvent_EventClaimed_LATE    UpdateEvent_EventClaimed_Result = 2
)

var UpdateEvent_EventClaimed_Result_name = map[int32]string{
	0: "CORRECT",
	1: "WRONG",
	2: "LATE",
}
var UpdateEvent_EventClaimed_Result_value = map[string]int32{
	"CORRECT": 0,
	"WRONG":   1,
	"LATE":    2,
}

func (x UpdateEvent_EventClaimed_Result) String() string {
	return proto.EnumName(UpdateEvent_EventClaimed_Result_name, int32(x))
}
func (UpdateEvent_EventClaimed_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 1, 0}
}

type Claim struct {
	Type  ClaimType `protobuf:"varint,1,opt,name=type,enum=ClaimType" json:"type,omitempty"`
	Cards []uint32  `protobuf:"varint,2,rep,packed,name=cards" json:"cards,omitempty"`
}

func (m *Claim) Reset()                    { *m = Claim{} }
func (m *Claim) String() string            { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()               {}
func (*Claim) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Claim) GetType() ClaimType {
	if m != nil {
		return m.Type
	}
	return ClaimType_CLAIM_MATCH
}

func (m *Claim) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

type UpdateEvent struct {
	// Types that are valid to be assigned to EventOneof:
	//	*UpdateEvent_Join
	//	*UpdateEvent_Claimed
	EventOneof isUpdateEvent_EventOneof `protobuf_oneof:"event_oneof"`
}

func (m *UpdateEvent) Reset()                    { *m = UpdateEvent{} }
func (m *UpdateEvent) String() string            { return proto.CompactTextString(m) }
func (*UpdateEvent) ProtoMessage()               {}
func (*UpdateEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isUpdateEvent_EventOneof interface {
	isUpdateEvent_EventOneof()
}

type UpdateEvent_Join struct {
	Join *UpdateEvent_EventJoin `protobuf:"bytes,1,opt,name=join,oneof"`
}
type UpdateEvent_Claimed struct {
	Claimed *UpdateEvent_EventClaimed `protobuf:"bytes,2,opt,name=claimed,oneof"`
}

func (*UpdateEvent_Join) isUpdateEvent_EventOneof()    {}
func (*UpdateEvent_Claimed) isUpdateEvent_EventOneof() {}

func (m *UpdateEvent) GetEventOneof() isUpdateEvent_EventOneof {
	if m != nil {
		return m.EventOneof
	}
	return nil
}

func (m *UpdateEvent) GetJoin() *UpdateEvent_EventJoin {
	if x, ok := m.GetEventOneof().(*UpdateEvent_Join); ok {
		return x.Join
	}
	return nil
}

func (m *UpdateEvent) GetClaimed() *UpdateEvent_EventClaimed {
	if x, ok := m.GetEventOneof().(*UpdateEvent_Claimed); ok {
		return x.Claimed
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateEvent_OneofMarshaler, _UpdateEvent_OneofUnmarshaler, _UpdateEvent_OneofSizer, []interface{}{
		(*UpdateEvent_Join)(nil),
		(*UpdateEvent_Claimed)(nil),
	}
}

func _UpdateEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateEvent)
	// event_oneof
	switch x := m.EventOneof.(type) {
	case *UpdateEvent_Join:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Join); err != nil {
			return err
		}
	case *UpdateEvent_Claimed:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Claimed); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UpdateEvent.EventOneof has unexpected type %T", x)
	}
	return nil
}

func _UpdateEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateEvent)
	switch tag {
	case 1: // event_oneof.join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateEvent_EventJoin)
		err := b.DecodeMessage(msg)
		m.EventOneof = &UpdateEvent_Join{msg}
		return true, err
	case 2: // event_oneof.claimed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateEvent_EventClaimed)
		err := b.DecodeMessage(msg)
		m.EventOneof = &UpdateEvent_Claimed{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateEvent)
	// event_oneof
	switch x := m.EventOneof.(type) {
	case *UpdateEvent_Join:
		s := proto.Size(x.Join)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpdateEvent_Claimed:
		s := proto.Size(x.Claimed)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UpdateEvent_EventJoin struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UpdateEvent_EventJoin) Reset()                    { *m = UpdateEvent_EventJoin{} }
func (m *UpdateEvent_EventJoin) String() string            { return proto.CompactTextString(m) }
func (*UpdateEvent_EventJoin) ProtoMessage()               {}
func (*UpdateEvent_EventJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *UpdateEvent_EventJoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateEvent_EventClaimed struct {
	Name   string                          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type   ClaimType                       `protobuf:"varint,2,opt,name=type,enum=ClaimType" json:"type,omitempty"`
	Result UpdateEvent_EventClaimed_Result `protobuf:"varint,3,opt,name=result,enum=UpdateEvent_EventClaimed_Result" json:"result,omitempty"`
}

func (m *UpdateEvent_EventClaimed) Reset()                    { *m = UpdateEvent_EventClaimed{} }
func (m *UpdateEvent_EventClaimed) String() string            { return proto.CompactTextString(m) }
func (*UpdateEvent_EventClaimed) ProtoMessage()               {}
func (*UpdateEvent_EventClaimed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *UpdateEvent_EventClaimed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateEvent_EventClaimed) GetType() ClaimType {
	if m != nil {
		return m.Type
	}
	return ClaimType_CLAIM_MATCH
}

func (m *UpdateEvent_EventClaimed) GetResult() UpdateEvent_EventClaimed_Result {
	if m != nil {
		return m.Result
	}
	return UpdateEvent_EventClaimed_CORRECT
}

type UpdateChange struct {
	// Types that are valid to be assigned to ChangeOneof:
	//	*UpdateChange_Deal
	//	*UpdateChange_Match
	//	*UpdateChange_Move
	ChangeOneof isUpdateChange_ChangeOneof `protobuf_oneof:"change_oneof"`
}

func (m *UpdateChange) Reset()                    { *m = UpdateChange{} }
func (m *UpdateChange) String() string            { return proto.CompactTextString(m) }
func (*UpdateChange) ProtoMessage()               {}
func (*UpdateChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isUpdateChange_ChangeOneof interface {
	isUpdateChange_ChangeOneof()
}

type UpdateChange_Deal struct {
	Deal *UpdateChange_ChangeDeal `protobuf:"bytes,1,opt,name=deal,oneof"`
}
type UpdateChange_Match struct {
	Match *UpdateChange_ChangeMatch `protobuf:"bytes,2,opt,name=match,oneof"`
}
type UpdateChange_Move struct {
	Move *UpdateChange_ChangeMove `protobuf:"bytes,3,opt,name=move,oneof"`
}

func (*UpdateChange_Deal) isUpdateChange_ChangeOneof()  {}
func (*UpdateChange_Match) isUpdateChange_ChangeOneof() {}
func (*UpdateChange_Move) isUpdateChange_ChangeOneof()  {}

func (m *UpdateChange) GetChangeOneof() isUpdateChange_ChangeOneof {
	if m != nil {
		return m.ChangeOneof
	}
	return nil
}

func (m *UpdateChange) GetDeal() *UpdateChange_ChangeDeal {
	if x, ok := m.GetChangeOneof().(*UpdateChange_Deal); ok {
		return x.Deal
	}
	return nil
}

func (m *UpdateChange) GetMatch() *UpdateChange_ChangeMatch {
	if x, ok := m.GetChangeOneof().(*UpdateChange_Match); ok {
		return x.Match
	}
	return nil
}

func (m *UpdateChange) GetMove() *UpdateChange_ChangeMove {
	if x, ok := m.GetChangeOneof().(*UpdateChange_Move); ok {
		return x.Move
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateChange) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateChange_OneofMarshaler, _UpdateChange_OneofUnmarshaler, _UpdateChange_OneofSizer, []interface{}{
		(*UpdateChange_Deal)(nil),
		(*UpdateChange_Match)(nil),
		(*UpdateChange_Move)(nil),
	}
}

func _UpdateChange_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateChange)
	// change_oneof
	switch x := m.ChangeOneof.(type) {
	case *UpdateChange_Deal:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Deal); err != nil {
			return err
		}
	case *UpdateChange_Match:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Match); err != nil {
			return err
		}
	case *UpdateChange_Move:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Move); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UpdateChange.ChangeOneof has unexpected type %T", x)
	}
	return nil
}

func _UpdateChange_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateChange)
	switch tag {
	case 1: // change_oneof.deal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateChange_ChangeDeal)
		err := b.DecodeMessage(msg)
		m.ChangeOneof = &UpdateChange_Deal{msg}
		return true, err
	case 2: // change_oneof.match
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateChange_ChangeMatch)
		err := b.DecodeMessage(msg)
		m.ChangeOneof = &UpdateChange_Match{msg}
		return true, err
	case 3: // change_oneof.move
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateChange_ChangeMove)
		err := b.DecodeMessage(msg)
		m.ChangeOneof = &UpdateChange_Move{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateChange_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateChange)
	// change_oneof
	switch x := m.ChangeOneof.(type) {
	case *UpdateChange_Deal:
		s := proto.Size(x.Deal)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpdateChange_Match:
		s := proto.Size(x.Match)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpdateChange_Move:
		s := proto.Size(x.Move)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UpdateChange_Position struct {
	X uint32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
}

func (m *UpdateChange_Position) Reset()                    { *m = UpdateChange_Position{} }
func (m *UpdateChange_Position) String() string            { return proto.CompactTextString(m) }
func (*UpdateChange_Position) ProtoMessage()               {}
func (*UpdateChange_Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *UpdateChange_Position) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *UpdateChange_Position) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type UpdateChange_ChangeDeal struct {
	Places []*UpdateChange_ChangeDeal_Place `protobuf:"bytes,1,rep,name=places" json:"places,omitempty"`
}

func (m *UpdateChange_ChangeDeal) Reset()                    { *m = UpdateChange_ChangeDeal{} }
func (m *UpdateChange_ChangeDeal) String() string            { return proto.CompactTextString(m) }
func (*UpdateChange_ChangeDeal) ProtoMessage()               {}
func (*UpdateChange_ChangeDeal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *UpdateChange_ChangeDeal) GetPlaces() []*UpdateChange_ChangeDeal_Place {
	if m != nil {
		return m.Places
	}
	return nil
}

type UpdateChange_ChangeDeal_Place struct {
	Position *UpdateChange_Position `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	Card     uint32                 `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
}

func (m *UpdateChange_ChangeDeal_Place) Reset()         { *m = UpdateChange_ChangeDeal_Place{} }
func (m *UpdateChange_ChangeDeal_Place) String() string { return proto.CompactTextString(m) }
func (*UpdateChange_ChangeDeal_Place) ProtoMessage()    {}
func (*UpdateChange_ChangeDeal_Place) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 1, 0}
}

func (m *UpdateChange_ChangeDeal_Place) GetPosition() *UpdateChange_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *UpdateChange_ChangeDeal_Place) GetCard() uint32 {
	if m != nil {
		return m.Card
	}
	return 0
}

type UpdateChange_ChangeMatch struct {
	Positions []*UpdateChange_Position `protobuf:"bytes,1,rep,name=positions" json:"positions,omitempty"`
}

func (m *UpdateChange_ChangeMatch) Reset()                    { *m = UpdateChange_ChangeMatch{} }
func (m *UpdateChange_ChangeMatch) String() string            { return proto.CompactTextString(m) }
func (*UpdateChange_ChangeMatch) ProtoMessage()               {}
func (*UpdateChange_ChangeMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *UpdateChange_ChangeMatch) GetPositions() []*UpdateChange_Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type UpdateChange_ChangeMove struct {
	Moves []*UpdateChange_ChangeMove_MoveOne `protobuf:"bytes,1,rep,name=moves" json:"moves,omitempty"`
}

func (m *UpdateChange_ChangeMove) Reset()                    { *m = UpdateChange_ChangeMove{} }
func (m *UpdateChange_ChangeMove) String() string            { return proto.CompactTextString(m) }
func (*UpdateChange_ChangeMove) ProtoMessage()               {}
func (*UpdateChange_ChangeMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 3} }

func (m *UpdateChange_ChangeMove) GetMoves() []*UpdateChange_ChangeMove_MoveOne {
	if m != nil {
		return m.Moves
	}
	return nil
}

type UpdateChange_ChangeMove_MoveOne struct {
	From *UpdateChange_Position `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To   *UpdateChange_Position `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
}

func (m *UpdateChange_ChangeMove_MoveOne) Reset()         { *m = UpdateChange_ChangeMove_MoveOne{} }
func (m *UpdateChange_ChangeMove_MoveOne) String() string { return proto.CompactTextString(m) }
func (*UpdateChange_ChangeMove_MoveOne) ProtoMessage()    {}
func (*UpdateChange_ChangeMove_MoveOne) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 3, 0}
}

func (m *UpdateChange_ChangeMove_MoveOne) GetFrom() *UpdateChange_Position {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *UpdateChange_ChangeMove_MoveOne) GetTo() *UpdateChange_Position {
	if m != nil {
		return m.To
	}
	return nil
}

type Update struct {
	// Types that are valid to be assigned to UpdateOneof:
	//	*Update_Change
	//	*Update_Event
	UpdateOneof isUpdate_UpdateOneof `protobuf_oneof:"update_oneof"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isUpdate_UpdateOneof interface {
	isUpdate_UpdateOneof()
}

type Update_Change struct {
	Change *UpdateChange `protobuf:"bytes,1,opt,name=change,oneof"`
}
type Update_Event struct {
	Event *UpdateEvent `protobuf:"bytes,2,opt,name=event,oneof"`
}

func (*Update_Change) isUpdate_UpdateOneof() {}
func (*Update_Event) isUpdate_UpdateOneof()  {}

func (m *Update) GetUpdateOneof() isUpdate_UpdateOneof {
	if m != nil {
		return m.UpdateOneof
	}
	return nil
}

func (m *Update) GetChange() *UpdateChange {
	if x, ok := m.GetUpdateOneof().(*Update_Change); ok {
		return x.Change
	}
	return nil
}

func (m *Update) GetEvent() *UpdateEvent {
	if x, ok := m.GetUpdateOneof().(*Update_Event); ok {
		return x.Event
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Update) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Update_OneofMarshaler, _Update_OneofUnmarshaler, _Update_OneofSizer, []interface{}{
		(*Update_Change)(nil),
		(*Update_Event)(nil),
	}
}

func _Update_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Update)
	// update_oneof
	switch x := m.UpdateOneof.(type) {
	case *Update_Change:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Change); err != nil {
			return err
		}
	case *Update_Event:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Event); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Update.UpdateOneof has unexpected type %T", x)
	}
	return nil
}

func _Update_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Update)
	switch tag {
	case 1: // update_oneof.change
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateChange)
		err := b.DecodeMessage(msg)
		m.UpdateOneof = &Update_Change{msg}
		return true, err
	case 2: // update_oneof.event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateEvent)
		err := b.DecodeMessage(msg)
		m.UpdateOneof = &Update_Event{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Update_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Update)
	// update_oneof
	switch x := m.UpdateOneof.(type) {
	case *Update_Change:
		s := proto.Size(x.Change)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Update_Event:
		s := proto.Size(x.Event)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Claim)(nil), "Claim")
	proto.RegisterType((*UpdateEvent)(nil), "UpdateEvent")
	proto.RegisterType((*UpdateEvent_EventJoin)(nil), "UpdateEvent.EventJoin")
	proto.RegisterType((*UpdateEvent_EventClaimed)(nil), "UpdateEvent.EventClaimed")
	proto.RegisterType((*UpdateChange)(nil), "UpdateChange")
	proto.RegisterType((*UpdateChange_Position)(nil), "UpdateChange.Position")
	proto.RegisterType((*UpdateChange_ChangeDeal)(nil), "UpdateChange.ChangeDeal")
	proto.RegisterType((*UpdateChange_ChangeDeal_Place)(nil), "UpdateChange.ChangeDeal.Place")
	proto.RegisterType((*UpdateChange_ChangeMatch)(nil), "UpdateChange.ChangeMatch")
	proto.RegisterType((*UpdateChange_ChangeMove)(nil), "UpdateChange.ChangeMove")
	proto.RegisterType((*UpdateChange_ChangeMove_MoveOne)(nil), "UpdateChange.ChangeMove.MoveOne")
	proto.RegisterType((*Update)(nil), "Update")
	proto.RegisterEnum("ClaimType", ClaimType_name, ClaimType_value)
	proto.RegisterEnum("UpdateEvent_EventClaimed_Result", UpdateEvent_EventClaimed_Result_name, UpdateEvent_EventClaimed_Result_value)
}

func init() { proto.RegisterFile("proto/triples.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x6d, 0xd7, 0x76, 0x92, 0x71, 0x5c, 0xc2, 0x80, 0x90, 0xf1, 0xa1, 0x44, 0x11, 0x2a,
	0x51, 0x84, 0x5c, 0x11, 0xa0, 0xe2, 0xc2, 0x21, 0x35, 0x11, 0x01, 0x35, 0x4d, 0xb5, 0x0a, 0xe2,
	0x84, 0x2a, 0x93, 0x6c, 0x5b, 0x23, 0xc7, 0x6b, 0x25, 0xdb, 0xa8, 0x79, 0x10, 0x9e, 0x80, 0x0b,
	0x2f, 0xc3, 0x1b, 0xf0, 0x30, 0x68, 0xff, 0x24, 0x4d, 0x0b, 0x16, 0x17, 0xc7, 0xfe, 0xe6, 0xb7,
	0xf3, 0xcd, 0x8c, 0xc7, 0x81, 0x07, 0xc5, 0x9c, 0x71, 0x76, 0xc0, 0xe7, 0x69, 0x91, 0xd1, 0x45,
	0x24, 0x9f, 0x5a, 0x6f, 0xc1, 0x89, 0xb3, 0x24, 0x9d, 0xe1, 0x1e, 0xd8, 0x7c, 0x55, 0xd0, 0xc0,
	0x6c, 0x9a, 0xed, 0xdd, 0x2e, 0x44, 0x52, 0x1d, 0xaf, 0x0a, 0x4a, 0xa4, 0x8e, 0x0f, 0xc1, 0x99,
	0x24, 0xf3, 0xe9, 0x22, 0xb0, 0x9a, 0x3b, 0x6d, 0x9f, 0xa8, 0x87, 0xd6, 0x2f, 0x0b, 0xbc, 0x4f,
	0xc5, 0x34, 0xe1, 0xb4, 0xbf, 0xa4, 0x39, 0xc7, 0xe7, 0x60, 0x7f, 0x63, 0x69, 0x2e, 0xb3, 0x78,
	0xdd, 0x47, 0xd1, 0x56, 0x2c, 0x92, 0xd7, 0x8f, 0x2c, 0xcd, 0x07, 0x06, 0x91, 0x14, 0xbe, 0x86,
	0xca, 0x44, 0xd8, 0xd0, 0x69, 0x60, 0xc9, 0x03, 0x8f, 0xff, 0x3e, 0x10, 0x2b, 0x60, 0x60, 0x90,
	0x35, 0x1b, 0x3e, 0x81, 0xda, 0x26, 0x17, 0x22, 0xd8, 0x79, 0x32, 0x53, 0x75, 0xd7, 0x88, 0xbc,
	0x0f, 0x7f, 0x9a, 0x50, 0xdf, 0x3e, 0xfc, 0x2f, 0x68, 0xd3, 0xb0, 0x55, 0xd2, 0xf0, 0x1b, 0x70,
	0xe7, 0x74, 0x71, 0x95, 0xf1, 0x60, 0x47, 0x12, 0xcd, 0xd2, 0xda, 0x22, 0x22, 0x39, 0xa2, 0xf9,
	0x56, 0x07, 0x5c, 0xa5, 0xa0, 0x07, 0x95, 0x78, 0x44, 0x48, 0x3f, 0x1e, 0x37, 0x0c, 0xac, 0x81,
	0xf3, 0x99, 0x8c, 0x4e, 0xde, 0x37, 0x4c, 0xac, 0x82, 0x7d, 0xdc, 0x1b, 0xf7, 0x1b, 0xd6, 0x91,
	0x0f, 0x1e, 0x15, 0xa9, 0xce, 0x58, 0x4e, 0xd9, 0x79, 0xeb, 0xb7, 0x0d, 0x75, 0x65, 0x13, 0x5f,
	0x26, 0xf9, 0x05, 0xc5, 0x08, 0xec, 0x29, 0x4d, 0x32, 0x3d, 0xd0, 0x20, 0xda, 0x0e, 0x46, 0xea,
	0xe7, 0x1d, 0x4d, 0x32, 0x31, 0x52, 0xc1, 0xe1, 0x0b, 0x70, 0x66, 0x09, 0x9f, 0x5c, 0xde, 0x19,
	0xe8, 0xad, 0x03, 0x43, 0x01, 0x0c, 0x0c, 0xa2, 0x48, 0x61, 0x31, 0x63, 0x4b, 0x2a, 0xdb, 0x2c,
	0xb1, 0x18, 0xb2, 0x25, 0x15, 0x16, 0x82, 0x0b, 0xf7, 0xa1, 0x7a, 0xca, 0x16, 0x29, 0x4f, 0x59,
	0x8e, 0x75, 0x30, 0xaf, 0x65, 0x6d, 0x3e, 0x31, 0xaf, 0xc5, 0xd3, 0x4a, 0x1a, 0xfb, 0xc4, 0x5c,
	0x85, 0xdf, 0x4d, 0x80, 0x9b, 0x0a, 0xf1, 0x10, 0xdc, 0x22, 0x4b, 0x26, 0x74, 0x11, 0x98, 0xcd,
	0x9d, 0xb6, 0xd7, 0xdd, 0x2b, 0xeb, 0x25, 0x3a, 0x15, 0x18, 0xd1, 0x74, 0x38, 0x02, 0x47, 0x0a,
	0xd8, 0x85, 0x6a, 0xa1, 0x7d, 0xef, 0xec, 0x97, 0x4e, 0xb1, 0xae, 0x8a, 0x6c, 0x38, 0xf1, 0xe2,
	0xc5, 0xa2, 0xea, 0xa2, 0xe4, 0x7d, 0x18, 0x83, 0xb7, 0x35, 0x07, 0x7c, 0x05, 0xb5, 0x35, 0xbe,
	0x2e, 0xad, 0x2c, 0xef, 0x0d, 0x18, 0xfe, 0xd8, 0x34, 0x27, 0x66, 0x83, 0x87, 0xe0, 0x88, 0xd9,
	0xac, 0x13, 0x34, 0xcb, 0x86, 0x18, 0x89, 0xcb, 0x28, 0xa7, 0x44, 0xe1, 0xe1, 0x17, 0xa8, 0x68,
	0x05, 0x3b, 0x60, 0x9f, 0xcf, 0xd9, 0xec, 0x3f, 0xad, 0x49, 0x06, 0xf7, 0xc1, 0xe2, 0x4c, 0xbf,
	0xe2, 0x32, 0xd2, 0xe2, 0xec, 0x68, 0x17, 0xea, 0x13, 0x29, 0xeb, 0xf5, 0xba, 0x00, 0x57, 0xc1,
	0xf8, 0x0c, 0x5c, 0x15, 0xd1, 0x7e, 0xfe, 0xad, 0x2c, 0x03, 0x83, 0xe8, 0x30, 0x3e, 0x05, 0x47,
	0x2e, 0xa8, 0x76, 0xab, 0x6f, 0x7f, 0x05, 0x62, 0x87, 0x64, 0x50, 0x18, 0x5d, 0x49, 0x5d, 0x19,
	0x75, 0x0e, 0xa0, 0xb6, 0xf9, 0x9e, 0xf0, 0x1e, 0x78, 0xf1, 0x71, 0xef, 0xc3, 0xf0, 0x6c, 0xd8,
	0x1b, 0xc7, 0x83, 0x86, 0x81, 0xf7, 0xc1, 0x57, 0xc2, 0xc9, 0x48, 0x49, 0xe6, 0x57, 0x57, 0xfe,
	0x1d, 0xbd, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xca, 0xe7, 0x6b, 0xdc, 0xa5, 0x04, 0x00, 0x00,
}
